site_name: ğŸ“ˆ mlrose-ky
nav:
  - ğŸšï¸ Home: index.md
  - ï¼Ÿ About: about.md
  - ğŸ”— Github: https://github.com/knakamura13/mlrose-ky

  - â†¯ Randomized Optimizations:
    - ğŸ¤” Optimization Problems: opt_probs.md
    - ğŸ›¹ Algorithms: algorithms.md
    - ğŸ“… Decay Schedules: decay.md
    - ğŸƒğŸ» Fitness Functions: fitness.md

  - ğŸ§  Neural Networks:
    - ğŸ“‰ Backpropagation using ROs: neural.md 

  - ğŸ§‘ğŸ»â€ğŸ’» Tutorials:
      - 1 - Getting Started: tutorial1.md
      - 2 - What is a Travelling Salesman Problem?: tutorial2.md
      - 3 - What is a Machine Learning Weight Optimization Problem?: tutorial3.md
      - 4 - How to use Runners for Optimization Problems?: runners.md

  - ğŸ“ Examples:
      - 1 - Runners in code: problem_examples.md
      - 2 - Fitness function in code: tutorial_examples.md
      - 3 - Using Neural Network Runners: nn_examples.md
      - 4 - How to use NeuralNetwork() with sklearn (EASY): nn_class_with_sklearn.md
theme: 
  name: readthedocs
  color_mode: auto
  navigation_depth: 6
  user_color_mode_toggle: true
  collapse_navigation: false
  highlightjs: true
  shortcuts:
    search: 75
markdown_extensions: 
  - nl2br
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      baselevel: 0
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  # - pymdownx.copybutton:
      # copy_on_click: true
plugins:
  - search
  - callouts
extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

